name: build-docs

on:
  workflow_call:

jobs:
  configure-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write


    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies on ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install cmake doxygen python3-pip
          pip3 install doxyqml


      - name: Create temp directories
        run: |
          cmake -E make_directory ${{runner.temp}}/build
      
      - name: Configure
        working-directory: ${{ runner.temp }}/build
        run: cmake -DBUILD_DOCS=ON -DBUILD_TESTING=OFF  ${{ github.workspace }}


      - name: Build docs
        working-directory: ${{ runner.temp }}/build
        run: cmake --build . --target doxygen_docs 


      - uses: actions/upload-artifact@v4
        with:
          name: 'docs'
          path:  ${{ github.workspace }}/doc/

