name: push-build-release
on: 
  workflow_call:
    inputs:
      qtModules:
        default: ''
        type: string  

jobs:
  build_wasm:
    runs-on: 'ubuntu-latest'
    permissions:
      pages: write      
      id-token: write 

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
        
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
          
      - name: Install dependencies on ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake

      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.25
          actions-cache-folder: 'emsdk-cache'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.5.0'
          host: 'linux'
          target: 'desktop'
          arch: 'wasm_singlethread'
          modules: ${{ inputs.qtModules }} 

      - name: Create build directory
        run:  cmake -E make_directory ${{runner.temp}}/build

      - name: Configure
        working-directory: ${{ runner.temp }}/build
        run: qt-cmake -G Ninja -DCMAKE_BUILD_TYPE="release"  -DCMAKE_INSTALL_PREFIX="../install" ${{ github.workspace }}
      
      - name: Build
        working-directory: ${{ runner.temp }}/build
        run: cmake --build .   
      
      - uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: ${{ github.workspace }}/wasm/ 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action

