name: push-build-release
on:
  workflow_call:
    inputs:
      qtVersion:
        default: '6.6.0'
        type: string
      qtArch:
        default: 'android_arm64_v8a'
        type: string
      qtModules:
        default: ''
        type: string
      qtTarget:
        default: ''
        type: string
      cmakeArgs:
        default: ''
        type: string
    secrets:
      QT_ANDROID_KEYSTORE_STORE_PASS:
        required: true

jobs:
  build_android:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies on ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake

      - name: Configure JDK
        uses: actions/setup-java@v4
        id: setup-jdk
        with:
          distribution: 'oracle'
          java-version: '20'

      - name: Configure SDK
        uses: android-actions/setup-android@v3
        id: setup-sdk

      - name: Configure NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
          add-to-path: false
          link-to-sdk: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: ${{ inputs.qtVersion }}
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          modules: ${{ inputs.qtModules }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: ${{ inputs.qtVersion }}
          host: 'linux'
          target: 'android'
          arch: ${{ inputs.qtArch }}
          modules: ${{ inputs.qtModules }}

      - name: Create build directory
        run: cmake -E make_directory ${{runner.temp}}/build

      - name: Configure
        working-directory: ${{ runner.temp }}/build
        run: |
          chmod +x ${{ github.workspace }}/../Qt/${{ inputs.qtVersion }}/${{ inputs.qtArch }}/bin/qt-cmake
          ${{ github.workspace }}/../Qt/${{ inputs.qtVersion }}/${{ inputs.qtArch }}/bin/qt-cmake -G Ninja  -DANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }} -DANDROID_SDK_ROOT=$ANDROID_SDK_ROOT -DQT_HOST_PATH=${{ github.workspace }}/../Qt/${{ inputs.qtVersion }}/gcc_64/ -DCMAKE_BUILD_TYPE="release" ${{ inputs.cmakeArgs }} -DCMAKE_INSTALL_PREFIX="../install" ${{ github.workspace }}

      - name: Build
        working-directory: ${{ runner.temp }}/build
        run: |
          cmake --build .

      - name: Build apk
        run: |
          ${{ github.workspace }}/../Qt/${{ inputs.qtVersion }}/gcc_64/bin/androiddeployqt --output ${{ runner.temp }}/build/android-build/ --input ${{ runner.temp }}/build/android-${{ inputs.qtTarget }}-deployment-settings.json  --jdk ${{ steps.setup-jdk.outputs.path }} --gradle --release --sign ${{ github.workspace }}/android/android_release.keystore  estervtech --storepass ${{ secrets.QT_ANDROID_KEYSTORE_STORE_PASS }}

      - name: Package
        working-directory: ${{ runner.temp }}/build/android-build/build/outputs/apk/release/
        run: |
          cmake -E make_directory ${{runner.temp}}/android-packages
          cmake -E tar c ${{runner.temp}}/android-packages/android_${{ inputs.qtArch }}.tar -- .


      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.qtArch }}_${{ inputs.qtTarget }}_${{ inputs.cmakeArgs }}
          path: ${{ runner.temp }}/android-packages/*

