name: push-build-release
on:
  workflow_call:
    inputs:
      os:
        default: 'ubuntu-latest'
        type: string
      qtModules:
        default: ''
        type: string 
      qtVersion:
        default: '6.7.0'
        type: string
      qmllint:
        default: false
        type: boolean


jobs:
  build_test_package:
    runs-on: ${{ inputs.os }}

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies on windows
        if: startsWith(inputs.os, 'windows')
        run: |
          choco install ninja cmake
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies on ubuntu
        if: startsWith(inputs.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake doxygen python3-pip
          pip3 install doxyqml
          
      - name: Install dependencies on macos
        if: startsWith(inputs.os, 'macos')
        run: |
          brew install cmake ninja

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: '==3.1.*'
          version: ${{ inputs.qtVersion }}
          modules: ${{ inputs.qtModules }}  
          tools: 'tools_ifw'

      - name: Configure-build-test
        env:
          CPACK_IFW_ROOT: "${{ github.workspace }}/../Qt/Tools/QtInstallerFramework/4.7"
        run: cmake --workflow  --preset default-develop

      - name: Create docs and changelog
        if: startsWith(inputs.os, 'ubuntu')
        run: |
          cmake -E make_directory ${{runner.temp}}/common
          cmake --workflow  --preset default-documentation
          cp -r doc/html ${{ runner.temp }}/common/
          git log $(git describe --tags --abbrev=0)^..HEAD --pretty=format:"* %h - %s (%an, %ar)" > ${{ runner.temp }}/common/CHANGELOG.md

      - name: Qmllint
        if: ${{ inputs.qmllint }}
        continue-on-error: true
        run: |
          cmake --workflow  --preset qmllint || true
          cp build/release/*_qmllint.json ${{ runner.temp }}/common/
          echo ${{ github.event.number }} >  ${{ runner.temp }}/common/pr_number

      - name: Package
        run: |
          cpack --preset default-develop 

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.os }}
          path: build/release/packages/*

      - uses: actions/upload-artifact@v4
        if: startsWith(inputs.os, 'ubuntu')
        with:
          name: "common"
          path: |
            ${{ runner.temp }}/common/*
