name: QML Lint 
on:
  workflow_call:

jobs:
  download-comment:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          name: common
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: ${{ runner.temp }}

      - name: Read pr variables
        id: getprv
        working-directory: ${{ runner.temp }}
        run: |
          echo "prn=$(cat pr_number)" >> $GITHUB_OUTPUT
          echo "prhr=$(cat pr-head-repo)" >> $GITHUB_OUTPUT
          echo "prhs=$(cat pr-head-sha)" >> $GITHUB_OUTPUT
          if [ -f "clang-fixes.yml" ]; then
           echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v4
        if: steps.getprv.outputs.exists == 'true'
        with:
          repository: ${{ steps.getprv.outputs.prhr }}
          ref: ${{ steps.getprv.outputs.prhs }}
          persist-credentials: false
      
      - name: Run clang-tidy-pr-comments action
        if: steps.getprv.outputs.exists == 'true'
        continue-on-error: true
        uses: platisd/clang-tidy-pr-comments@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clang_tidy_fixes: ${{ runner.temp }}/clang-fixes.yml
          pull_request_id: ${{ steps.getprv.outputs.prn }}
          request_changes: true

      - name: 'QML'
        uses: EddyTheCo/qmllint-action/@v0.1.0
        with:
          jsondir: ${{ runner.temp }}
          pr_number: ${{ steps.getprn.outputs.prn }}
