name: QML Lint 
on:
  workflow_call:

jobs:
  download-comment:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          name: common
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Read pr number
        id: getprn
        run: |
          cat pr_number
          echo "prn=$(cat pr_number)" >> $GITHUB_OUTPUT

      - name: 'Run reviewer'
        uses: EddyTheCo/qmllint-action/@v0.1.0
        with:
          jsondir:  ${{ github.workspace }}
          pr_number: ${{ steps.getprn.outputs.prn }}

